import cardOne from "@/public/images/mock_cardTitle_1.jpg";
import cardTwo from "@/public/images/mock_cardTitle_2.jpg";
import cardThree from "@/public/images/mock_cardTitle_3.jpg";
import cardFour from "@/public/images/mock_cardTitle_4.jpg";
import cardFive from "@/public/images/mock_cardTitle_5.jpg";

export const myProjectList = {
  count: 10,
  data: [
    {
      id: 0,
      userId: 1,
      titleImage: cardOne,
      stackList: ["React", "Node.js", "Figma"],
      wishCount: 10,
      isWish: true,
      projectTitle: "Hello Fruits",
      subDescription: "간단한 프로젝트입니다.",
      viewCount: 100,
      createdAt: "2024-05-27T10:04:08.409124+00:00",
    },
    {
      id: 1,
      userId: 1,
      titleImage: cardTwo,
      stackList: ["React"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Animals",
      subDescription: "심오한 프로젝트입니다.",
      viewCount: 53,
      createdAt: "2024-06-27T10:04:08.409124+00:00",
    },
    {
      id: 2,
      userId: 1,
      titleImage: cardThree,
      stackList: ["React"],
      wishCount: 52,
      isWish: true,
      projectTitle: "Hello Characters",
      subDescription: "어지러운 프로젝트입니다.",
      viewCount: 4,
      createdAt: "2024-05-28T10:04:08.409124+00:00",
    },
    {
      id: 3,
      userId: 1,
      titleImage: cardFour,
      stackList: ["React"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Been! Actually, I have a lot of things to talk about",
      subDescription: "어려운 프로젝트입니다. 사실 할 말 많은데 여기는 너무 짧게",
      viewCount: 1,
      createdAt: "2024-05-27T12:04:08.409124+00:00",
    },
    {
      id: 4,
      userId: 1,
      titleImage: cardFive,
      stackList: ["React", "Node.js", "Figma", "Spring", "SQL"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Been",
      subDescription: "쉬운 프로젝트입니다. ",
      viewCount: 100000,
      createdAt: "2023-12-27T10:04:08.409124+00:00",
    },
    {
      id: 5,
      userId: 1,
      titleImage: cardOne,
      stackList: ["React", "Node.js", "Figma"],
      wishCount: 10,
      isWish: true,
      projectTitle: "Hello Fruits",
      subDescription: "간단한 프로젝트입니다.",
      viewCount: 100,
      createdAt: "2023-11-27T10:04:08.409124+00:00",
    },
    {
      id: 6,
      userId: 1,
      titleImage: cardTwo,
      stackList: ["React"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Animals",
      subDescription: "심오한 프로젝트입니다.",
      viewCount: 53,
      createdAt: "2024-02-27T10:04:08.409124+00:00",
    },
    {
      id: 7,
      userId: 1,
      titleImage: cardThree,
      stackList: ["React"],
      wishCount: 52,
      isWish: true,
      projectTitle: "Hello Characters",
      subDescription: "어지러운 프로젝트입니다.",
      viewCount: 4,
      createdAt: "2024-01-20T10:04:08.409124+00:00",
    },
    {
      id: 8,
      userId: 1,
      titleImage: cardFour,
      stackList: ["React"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Been! Actually, I have a lot of things to talk about",
      subDescription: "어려운 프로젝트입니다. 사실 할 말 많은데 여기는 너무 짧게",
      viewCount: 1,
      createdAt: "2024-04-21T10:04:08.409124+00:00",
    },
    {
      id: 9,
      userId: 1,
      titleImage: cardFive,
      stackList: ["React", "Node.js", "Figma", "Spring", "SQL"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Been",
      subDescription: "쉬운 프로젝트입니다. ",
      viewCount: 100000,
      createdAt: "2024-05-25T10:04:08.409124+00:00",
    },
  ],
};

export const wishProjectList = {
  count: 6,
  data: [
    {
      id: 0,
      userId: 1,
      titleImage: cardOne,
      stackList: ["React", "Node.js", "Figma"],
      wishCount: 10,
      isWish: true,
      projectTitle: "Hello Fruits",
      subDescription: "간단한 프로젝트입니다.",
      viewCount: 100,
      createdAt: "2024-05-27T10:04:08.409124+00:00",
    },
    {
      id: 1,
      userId: 1,
      titleImage: cardTwo,
      stackList: ["React"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Animals",
      subDescription: "심오한 프로젝트입니다.",
      viewCount: 53,
      createdAt: "2024-06-27T10:04:08.409124+00:00",
    },
    {
      id: 2,
      userId: 1,
      titleImage: cardThree,
      stackList: ["React"],
      wishCount: 52,
      isWish: true,
      projectTitle: "Hello Characters",
      subDescription: "어지러운 프로젝트입니다.",
      viewCount: 4,
      createdAt: "2024-05-28T10:04:08.409124+00:00",
    },
    {
      id: 3,
      userId: 1,
      titleImage: cardFour,
      stackList: ["React"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Been! Actually, I have a lot of things to talk about",
      subDescription: "어려운 프로젝트입니다. 사실 할 말 많은데 여기는 너무 짧게",
      viewCount: 1,
      createdAt: "2024-05-27T12:04:08.409124+00:00",
    },
    {
      id: 4,
      userId: 1,
      titleImage: cardFive,
      stackList: ["React", "Node.js", "Figma", "Spring", "SQL"],
      wishCount: 52,
      isWish: false,
      projectTitle: "Hello Been",
      subDescription: "쉬운 프로젝트입니다. ",
      viewCount: 100000,
      createdAt: "2023-12-27T10:04:08.409124+00:00",
    },
    {
      id: 5,
      userId: 1,
      titleImage: cardOne,
      stackList: ["React", "Node.js", "Figma"],
      wishCount: 10,
      isWish: true,
      projectTitle: "Hello Fruits",
      subDescription: "간단한 프로젝트입니다.",
      viewCount: 100,
      createdAt: "2023-11-27T10:04:08.409124+00:00",
    },
  ],
};
