const JOB_CATEGORIES = {
  ALL: "ALL",
  FRONTEND: "FRONTEND",
  BACKEND: "BACKEND",
  DESIGNER: "DESIGNER",
  IOS: "IOS",
  ANDROID: "ANDROID",
  DEVOPS: "DEVOPS",
  PLANNER: "PLANNER",
  FULLSTACK: "FULLSTACK",
  ETC: "ETC",
};

export default JOB_CATEGORIES;
